<?php

namespace Database\Seeders;

use App\Models\Chats;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChatsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Chats::insert([
            [
                'student_id' => 1,
                'reply_to' => null,
                'message' => 'Hello, I need help with my assignment.',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => null,
                'message' => 'Hello',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => null,
                'message' => 'Can we schedule a meeting?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => null,
                'reply_to' => 2,
                'message' => 'Ok!',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 3,
                'reply_to' => null,
                'message' => 'I need clarification on the project guidelines.',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 4,
                'reply_to' => null,
                'message' => 'Can someone help me with this equation?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 1,
                'reply_to' => 1,
                'message' => 'Sure, what do you need help with?',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => null,
                'message' => 'I have a question about the assignment.',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 3,
                'reply_to' => 3,
                'message' => 'The part about the group work is unclear.',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 4,
                'reply_to' => 4,
                'message' => 'I can help! What’s the equation?',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => null,
                'message' => 'What time is the meeting scheduled?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 1,
                'reply_to' => 7,
                'message' => 'The meeting is at 3 PM.',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 3,
                'reply_to' => null,
                'message' => 'Thanks for the clarification!',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 4,
                'reply_to' => null,
                'message' => 'Can someone explain the homework?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 1,
                'reply_to' => null,
                'message' => 'I have some notes on the homework.',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => 11,
                'message' => 'Could you share them?',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 3,
                'reply_to' => null,
                'message' => 'What’s the topic of the next class?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 4,
                'reply_to' => 10,
                'message' => 'The homework is about integrals.',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 1,
                'reply_to' => 13,
                'message' => 'Next class will cover derivatives.',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => null,
                'message' => 'Can anyone recommend a good textbook?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 3,
                'reply_to' => 16,
                'message' => 'I found "Calculus Made Easy" very helpful.',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 4,
                'reply_to' => null,
                'message' => 'Does anyone have the lab manual?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 1,
                'reply_to' => 18,
                'message' => 'I have it, I can share a copy.',
                'sent_at' => now(),
                'is_reply' => true,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'student_id' => 2,
                'reply_to' => null,
                'message' => 'Is the assignment deadline extended?',
                'sent_at' => now(),
                'is_reply' => false,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
