<?php

namespace Database\Seeders;

use App\Models\TeacherEvaluations;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TeacherEvaluationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TeacherEvaluations::insert([
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 1,
                'first_rating_level' => 4,
                'second_rating_level' => 5,
                'third_rating_level' => 3,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 2,
                'first_rating_level' => 4,
                'second_rating_level' => 5,
                'third_rating_level' => 3,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 3,
                'first_rating_level' => 4,
                'second_rating_level' => 5,
                'third_rating_level' => 3,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 4,
                'first_rating_level' => 3,
                'second_rating_level' => 4,
                'third_rating_level' => 3,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 4,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 5,
                'first_rating_level' => 5,
                'second_rating_level' => 4,
                'third_rating_level' => 4,
                'fourth_rating_level' => 5,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 6,
                'first_rating_level' => 2,
                'second_rating_level' => 3,
                'third_rating_level' => 2,
                'fourth_rating_level' => 3,
                'fifth_rating_level' => 4,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 7,
                'first_rating_level' => 4,
                'second_rating_level' => 4,
                'third_rating_level' => 4,
                'fourth_rating_level' => 5,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 8,
                'first_rating_level' => 3,
                'second_rating_level' => 3,
                'third_rating_level' => 4,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 3,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 9,
                'first_rating_level' => 5,
                'second_rating_level' => 4,
                'third_rating_level' => 5,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 1,
                'student_id' => 10,
                'first_rating_level' => 2,
                'second_rating_level' => 2,
                'third_rating_level' => 3,
                'fourth_rating_level' => 2,
                'fifth_rating_level' => 3,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 11,
                'first_rating_level' => 3,
                'second_rating_level' => 4,
                'third_rating_level' => 5,
                'fourth_rating_level' => 3,
                'fifth_rating_level' => 4,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 12,
                'first_rating_level' => 4,
                'second_rating_level' => 5,
                'third_rating_level' => 4,
                'fourth_rating_level' => 5,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 13,
                'first_rating_level' => 3,
                'second_rating_level' => 4,
                'third_rating_level' => 3,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 4,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 14,
                'first_rating_level' => 5,
                'second_rating_level' => 4,
                'third_rating_level' => 5,
                'fourth_rating_level' => 5,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 15,
                'first_rating_level' => 4,
                'second_rating_level' => 4,
                'third_rating_level' => 4,
                'fourth_rating_level' => 3,
                'fifth_rating_level' => 4,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 16,
                'first_rating_level' => 2,
                'second_rating_level' => 2,
                'third_rating_level' => 3,
                'fourth_rating_level' => 2,
                'fifth_rating_level' => 3,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 17,
                'first_rating_level' => 4,
                'second_rating_level' => 4,
                'third_rating_level' => 5,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 18,
                'first_rating_level' => 3,
                'second_rating_level' => 4,
                'third_rating_level' => 3,
                'fourth_rating_level' => 4,
                'fifth_rating_level' => 3,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 19,
                'first_rating_level' => 5,
                'second_rating_level' => 5,
                'third_rating_level' => 4,
                'fourth_rating_level' => 5,
                'fifth_rating_level' => 5,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'create_teacher_evaluation_id' => 2,
                'student_id' => 20,
                'first_rating_level' => 2,
                'second_rating_level' => 3,
                'third_rating_level' => 2,
                'fourth_rating_level' => 3,
                'fifth_rating_level' => 2,
                'evaluation_date' => now()->toDateString(),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ]);        
    }
}
