<?php
namespace Database\Seeders;

use App\Models\Teachers;
use Illuminate\Database\Seeder;

class TeachersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Teachers::insert([
            [
                'code' => 'T001',
                'name' => 'Thầy Zách',
                'image' => null,
                'email' => 'luphathuyne@gmail.com',
                'phone' => '0945567048',
                'address' => '123 Main St, Anytown, USA',
                'current_address' => '123 Current St, Anytown, USA',
                'gender' => 'Male',
                'date_of_birth' => '1980-01-01',
                'qualifications' => 'MSc in Education',
                'cccd_front' => 'cccd_front_T001.jpg',
                'cccd_back' => 'cccd_back_T001.jpg',
                'bio' => 'An experienced teacher with over 20 years in the education field.',
                'course_id' => 1,
                'role_id' => 3,
                'OTP' => rand(111111, 999999),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'T002',
                'name' => 'Nguyen Thanh Tam',
                'image' => null,
                'email' => 'thanhtamnguyen@gmail.com',
                'phone' => '1234567890',
                'address' => '456 Elm St, Anytown, USA',
                'current_address' => '456 Current St, Anytown, USA',
                'gender' => 'Female',
                'date_of_birth' => '1985-05-15',
                'qualifications' => 'PhD in Mathematics',
                'cccd_front' => 'cccd_front_T002.jpg',
                'cccd_back' => 'cccd_back_T002.jpg',
                'bio' => 'Specializes in advanced mathematical concepts and research.',
                'course_id' => 1,
                'role_id' => 3,
                'OTP' => rand(111111, 999999),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'T003',
                'name' => 'Pham Kha Nam',
                'image' => null,
                'email' => 'namkhapham@gmail.com',
                'phone' => '0987654321',
                'address' => '789 Oak St, Anytown, USA',
                'current_address' => '789 Current St, Anytown, USA',
                'gender' => 'Male',
                'date_of_birth' => '1990-07-20',
                'qualifications' => 'BSc in Physics',
                'cccd_front' => 'cccd_front_T003.jpg',
                'cccd_back' => 'cccd_back_T003.jpg',
                'bio' => 'Passionate about teaching physics and conducting experiments.',
                'course_id' => 2,
                'role_id' => 3,
                'OTP' => rand(111111, 999999),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'T004',
                'name' => 'Phan Van Tinh',
                'image' => null,
                'email' => 'tinhphanvan@gmail.com',
                'phone' => '0987654321',
                'address' => '321 Pine St, Anytown, USA',
                'current_address' => '321 Current St, Anytown, USA',
                'gender' => 'Male',
                'date_of_birth' => '1982-11-11',
                'qualifications' => 'MA in Literature',
                'cccd_front' => 'cccd_front_T004.jpg',
                'cccd_back' => 'cccd_back_T004.jpg',
                'bio' => 'Expert in literature with a focus on modern poetry.',
                'course_id' => 2,
                'role_id' => 3,
                'OTP' => rand(111111, 999999),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'T005',
                'name' => 'Le Ngoc Dao',
                'image' => null,
                'email' => 'daolengoc@gmail.com',
                'phone' => '0987654321',
                'address' => '654 Willow St, Anytown, USA',
                'current_address' => '654 Current St, Anytown, USA',
                'gender' => 'Female',
                'date_of_birth' => '1975-04-04',
                'qualifications' => 'PhD in Chemistry',
                'cccd_front' => 'cccd_front_T005.jpg',
                'cccd_back' => 'cccd_back_T005.jpg',
                'bio' => 'Dedicated to teaching chemistry and fostering a love for science.',
                'course_id' => 1,
                'role_id' => 3,
                'OTP' => rand(111111, 999999),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'code' => 'T006',
                'name' => 'Tran Hoang Le Chi',
                'image' => null,
                'email' => 'lechitranhoang@gmail.com',
                'phone' => '0987654321',
                'address' => '987 Maple St, Anytown, USA',
                'current_address' => '987 Current St, Anytown, USA',
                'gender' => 'Female',
                'date_of_birth' => '1988-09-09',
                'qualifications' => 'MEd in Education',
                'cccd_front' => 'cccd_front_T006.jpg',
                'cccd_back' => 'cccd_back_T006.jpg',
                'bio' => 'Focused on innovative teaching methods and student engagement.',
                'course_id' => 1,
                'role_id' => 3,
                'OTP' => rand(111111, 999999),
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}

